apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-app
  minReplicas: 6
  maxReplicas: 46
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
